#ifndef CONTROLLER_DATA_CONF_H
#define CONTROLLER_DATA_CONF_H

#include <sdkconfig.h>

#ifndef CONFIG_MROS_ENABLE_CONTROLLER_DATA_PUBLISH
#define ENABLE_CONTROLLER_DATA_PUBLISH 0
#else
#define ENABLE_CONTROLLER_DATA_PUBLISH 1
#ifdef CONFIG_MROS_CONTROLLER_DATA_TOPIC
#define CONTROLLER_DATA_TOPIC CONFIG_MROS_CONTROLLER_DATA_TOPIC
#else
#define CONTROLLER_DATA_TOPIC "ctrl_data"
#endif
#ifdef CONFIG_MROS_CONTROLLER_DATA_PUBLISHER_PERIOD_MS
#define CONTROLLER_DATA_PUBLISHER_PERIOD_MS CONFIG_MROS_CONTROLLER_DATA_PUBLISHER_PERIOD_MS
#else
#define CONTROLLER_DATA_PUBLISHER_PERIOD_MS 100
#endif
#ifdef CONFIG_MROS_CONTROLLER_DATA_SIZE
#define CONTROLLER_DATA_SIZE CONFIG_MROS_CONTROLLER_DATA_SIZE
#else
#define CONTROLLER_DATA_SIZE 7
#endif
#endif

#endif