#ifndef MROS_CONF_H
#define MROS_CONF_H

#include <sdkconfig.h>

#ifdef CONFIG_MROS_LOGGER_TAG
#define MROS_LOGGER_TAG CONFIG_MROS_LOGGER_TAG
#else
#define MROS_LOGGER_TAG "MROS"
#endif

#ifdef CONFIG_MROS_EXECUTOR_SPIN_TIMEOUT_MS
#define MROS_EXECUTOR_SPIN_TIMEOUT_MS CONFIG_MROS_EXECUTOR_SPIN_TIMEOUT_MS
#else
#define MROS_EXECUTOR_SPIN_TIMEOUT_MS 10
#endif

#ifdef CONFIG_MROS_AGENT_PERIOD_MS
#define MROS_AGENT_PERIOD_MS CONFIG_MROS_AGENT_PERIOD_MS
#else
#define MROS_AGENT_PERIOD_MS 5000
#endif

#ifdef CONFIG_MROS_SERIAL_PORT
#define MROS_SERIAL_PORT CONFIG_MROS_SERIAL_PORT
#else
#define MROS_SERIAL_PORT UART_NUM_0
#endif

#ifdef CONFIG_MROS_NODE_NAME
#define MROS_NODE_NAME CONFIG_MROS_NODE_NAME
#else
#define MROS_NODE_NAME "mros_node"
#endif

#ifdef CONFIG_MROS_NODE_NAMESPACE
#define MROS_NODE_NAMESPACE CONFIG_MROS_NODE_NAMESPACE
#else
#define MROS_NODE_NAMESPACE "mros_namespace"
#endif

#ifdef CONFIG_MROS_CMD_VEL_TOPIC
#define MROS_CMD_VEL_TOPIC CONFIG_MROS_CMD_VEL_TOPIC
#else
#define MROS_CMD_VEL_TOPIC "cmd_vel"
#endif

#ifdef CONFIG_MROS_ODOMETRY_TOPIC
#define MROS_ODOMETRY_TOPIC CONFIG_MROS_ODOMETRY_TOPIC
#else
#define MROS_ODOMETRY_TOPIC "odom"
#endif

#ifdef CONFIG_MROS_ODOM_FRAME_ID
#define MROS_ODOM_FRAME_ID CONFIG_MROS_ODOM_FRAME_ID
#else
#define MROS_ODOM_FRAME_ID "odom"
#endif

#ifdef CONFIG_MROS_BASE_FRAME_ID
#define MROS_BASE_FRAME_ID CONFIG_MROS_BASE_FRAME_ID
#else
#define MROS_BASE_FRAME_ID "base_link"
#endif

#ifdef CONFIG_MROS_ODOM_PUBLISHER_PERIOD_MS
#define MROS_ODOM_PUBLISHER_PERIOD_MS CONFIG_MROS_ODOM_PUBLISHER_PERIOD_MS
#else
#define MROS_ODOM_PUBLISHER_PERIOD_MS 100
#endif

#ifdef CONFIG_MROS_MAX_TIME_SYNC_TIMEOUT_MS
#define MROS_MAX_TIME_SYNC_TIMEOUT_MS CONFIG_MROS_MAX_TIME_SYNC_TIMEOUT_MS
#else
#define MROS_MAX_TIME_SYNC_TIMEOUT_MS 1000
#endif

#ifdef CONFIG_MROS_PING_TIMEOUT_MS
#define MROS_PING_TIMEOUT_MS CONFIG_MROS_PING_TIMEOUT_MS
#else
#define MROS_PING_TIMEOUT_MS 1000
#endif

#ifdef CONFIG_MROS_MAX_PING_ATTEMPTS
#define MROS_MAX_PING_ATTEMPTS CONFIG_MROS_MAX_PING_ATTEMPTS
#else
#define MROS_MAX_PING_ATTEMPTS 3
#endif

#ifdef CONFIG_MROS_EXECUTOR_TASK_NAME
#define MROS_EXECUTOR_TASK_NAME CONFIG_MROS_EXECUTOR_TASK_NAME
#else
#define MROS_EXECUTOR_TASK_NAME "mros_executor_task"
#endif

#ifdef CONFIG_MROS_EXECUTOR_TASK_STACK_SIZE
#define MROS_EXECUTOR_TASK_STACK_SIZE CONFIG_MROS_EXECUTOR_TASK_STACK_SIZE
#else
#define MROS_EXECUTOR_TASK_STACK_SIZE 4096
#endif

#ifdef CONFIG_MROS_EXECUTOR_TASK_PRIORITY
#define MROS_EXECUTOR_TASK_PRIORITY CONFIG_MROS_EXECUTOR_TASK_PRIORITY
#else
#define MROS_EXECUTOR_TASK_PRIORITY 6
#endif

#ifdef CONFIG_MROS_AGENT_TASK_NAME
#define MROS_AGENT_TASK_NAME CONFIG_MROS_AGENT_TASK_NAME
#else
#define MROS_AGENT_TASK_NAME "mros_agent_task"
#endif

#ifdef CONFIG_MROS_AGENT_TASK_STACK_SIZE
#define MROS_AGENT_TASK_STACK_SIZE CONFIG_MROS_AGENT_TASK_STACK_SIZE
#else
#define MROS_AGENT_TASK_STACK_SIZE 4096
#endif

#ifdef CONFIG_MROS_AGENT_TASK_PRIORITY
#define MROS_AGENT_TASK_PRIORITY CONFIG_MROS_AGENT_TASK_PRIORITY
#else
#define MROS_AGENT_TASK_PRIORITY 4
#endif

#define MROS_MAX_PING_TIMEOUT_MS MROS_PING_TIMEOUT_MS *MROS_MAX_PING_ATTEMPTS
#define MROS_MAX_TIMEOUT_MS MAX(MROS_MAX_TIME_SYNC_TIMEOUT_MS, MROS_MAX_PING_TIMEOUT_MS)

#endif // MROS_CONF_H