#ifndef MROS_CONF_H
#define MROS_CONF_H

#include <sdkconfig.h>

#define MROS_LOGGER_TAG "MROS"

// micro-ROS timing constants
#define MROS_EXECUTOR_SPIN_TIMEOUT_MS 10
#define MROS_AGENT_PERIOD_MS 5000
#define MROS_MAX_TIME_SYNC_TIMEOUT_MS 1000
#define MROS_PING_TIMEOUT_MS 1000
#define MROS_MAX_PING_ATTEMPTS 3
#define MROS_SERIAL_PORT UART_NUM_0

// micro-ROS task configuration
#define MROS_EXECUTOR_TASK_NAME "mros_executor_task"
#define MROS_EXECUTOR_TASK_STACK_SIZE 4096
#define MROS_EXECUTOR_TASK_PRIORITY 6
#define MROS_AGENT_TASK_NAME "mros_agent_task"
#define MROS_AGENT_TASK_STACK_SIZE 4096
#define MROS_AGENT_TASK_PRIORITY 4

// User-configurable via Kconfig

#ifdef CONFIG_MROS_IMU_TOPIC
#define MROS_IMU_TOPIC CONFIG_MROS_IMU_TOPIC
#else
#define MROS_IMU_TOPIC "imu"
#endif

#ifdef CONFIG_MROS_IMU_PUBLISHER_PERIOD_MS
#define MROS_IMU_PUBLISHER_PERIOD_MS CONFIG_MROS_IMU_PUBLISHER_PERIOD_MS
#else
#define MROS_IMU_PUBLISHER_PERIOD_MS 100
#endif

#ifdef CONFIG_MROS_IMU_FRAME_ID
#define MROS_IMU_FRAME_ID CONFIG_MROS_IMU_FRAME_ID
#else
#define MROS_IMU_FRAME_ID "imu"
#endif

#ifdef CONFIG_MROS_NODE_NAME
#define MROS_NODE_NAME CONFIG_MROS_NODE_NAME
#else
#define MROS_NODE_NAME "car_node"
#endif

#ifdef CONFIG_MROS_NODE_NAMESPACE
#define MROS_NODE_NAMESPACE CONFIG_MROS_NODE_NAMESPACE
#else
#define MROS_NODE_NAMESPACE ""
#endif

#ifdef CONFIG_MROS_CMD_VEL_TOPIC
#define MROS_CMD_VEL_TOPIC CONFIG_MROS_CMD_VEL_TOPIC
#else
#define MROS_CMD_VEL_TOPIC "cmd_vel"
#endif

#ifdef CONFIG_MROS_ODOMETRY_TOPIC
#define MROS_ODOMETRY_TOPIC CONFIG_MROS_ODOMETRY_TOPIC
#else
#define MROS_ODOMETRY_TOPIC "odom"
#endif

#ifdef CONFIG_MROS_ODOMETRY_FRAME_ID
#define MROS_ODOM_FRAME_ID CONFIG_MROS_ODOMETRY_FRAME_ID
#else
#define MROS_ODOM_FRAME_ID "odom"
#endif

#ifdef CONFIG_MROS_BASE_FRAME_ID
#define MROS_BASE_FRAME_ID CONFIG_MROS_BASE_FRAME_ID
#else
#define MROS_BASE_FRAME_ID "base_link"
#endif

#ifdef CONFIG_MROS_ODOM_PUBLISHER_PERIOD_MS
#define MROS_ODOM_PUBLISHER_PERIOD_MS CONFIG_MROS_ODOM_PUBLISHER_PERIOD_MS
#else
#define MROS_ODOM_PUBLISHER_PERIOD_MS 100
#endif

// Computed timeouts
#define MROS_MAX_PING_TIMEOUT_MS (MROS_PING_TIMEOUT_MS * MROS_MAX_PING_ATTEMPTS)
#define MROS_MAX_TIMEOUT_MS MAX(MROS_MAX_TIME_SYNC_TIMEOUT_MS, MROS_MAX_PING_TIMEOUT_MS)

#endif // MROS_CONF_H