#ifndef ODRIVE_CONF_H
#define ODRIVE_CONF_H

#include "utils/math_utils.h"
#include <sdkconfig.h>

#ifdef CONFIG_ODRIVE_LOGGER_TAG
#define ODRIVE_LOGGER_TAG CONFIG_ODRIVE_LOGGER_TAG
#else
#define ODRIVE_LOGGER_TAG "ODRIVE"
#endif

#ifdef CONFIG_ODRIVE_HEARTBEAT_TIMEOUT_MS
#define ODRIVE_HEARTBEAT_TIMEOUT_MS CONFIG_ODRIVE_HEARTBEAT_TIMEOUT_MS
#else
#define ODRIVE_HEARTBEAT_TIMEOUT_MS 200
#endif

#ifdef CONFIG_ODRIVE_ENCODER_ESTIMATES_TIMEOUT_MS
#define ODRIVE_ENCODER_ESTIMATES_TIMEOUT_MS CONFIG_ODRIVE_ENCODER_ESTIMATES_TIMEOUT_MS
#else
#define ODRIVE_ENCODER_ESTIMATES_TIMEOUT_MS 50
#endif

#ifdef CONFIG_ODRIVE_MAX_CALIBRATION_TIME_S
#define ODRIVE_MAX_CALIBRATION_TIME_S CONFIG_ODRIVE_MAX_CALIBRATION_TIME_S
#else
#define ODRIVE_MAX_CALIBRATION_TIME_S 20
#endif

#ifdef CONFIG_ODRIVE_MAX_AXIS_STATE_CHANGE_TIME_S
#define ODRIVE_MAX_AXIS_STATE_CHANGE_TIME_S CONFIG_ODRIVE_MAX_AXIS_STATE_CHANGE_TIME_S
#else
#define ODRIVE_MAX_AXIS_STATE_CHANGE_TIME_S 1
#endif

#ifdef CONFIG_ODRIVE_QUEUE_ACCESS_TIMEOUT_MS
#define ODRIVE_QUEUE_ACCESS_TIMEOUT_MS CONFIG_ODRIVE_QUEUE_ACCESS_TIMEOUT_MS
#else
#define ODRIVE_QUEUE_ACCESS_TIMEOUT_MS 10
#endif

#ifdef CONFIG_ODRIVE_CAN_DATA_LENGTH
#define ODRIVE_CAN_DATA_LENGTH CONFIG_ODRIVE_CAN_DATA_LENGTH
#else
#define ODRIVE_CAN_DATA_LENGTH 8
#endif

#ifdef CONFIG_ODRIVE_CAN_MAX_RTR_RESPONSE_TIME_MS
#define ODRIVE_CAN_MAX_RTR_RESPONSE_TIME_MS CONFIG_ODRIVE_CAN_MAX_RTR_RESPONSE_TIME_MS
#else // The max time to wait to get a response to an RTR request from ODrive
#define ODRIVE_CAN_MAX_RTR_RESPONSE_TIME_MS 500
#endif

#ifdef CONFIG_ODRIVE_CAN_MAX_TRANSMIT_QUEUE_TIMEOUT_MS
#define ODRIVE_CAN_MAX_TRANSMIT_QUEUE_TIMEOUT_MS CONFIG_ODRIVE_CAN_MAX_TRANSMIT_QUEUE_TIMEOUT_MS
#else // The max time to wait for acessing the CAN driver transmit queue
#define ODRIVE_CAN_MAX_TRANSMIT_QUEUE_TIMEOUT_MS 10
#endif

#ifdef CONFIG_ODRIVE_CAN_MAX_RECEIVE_QUEUE_TIMEOUT_MS
#define ODRIVE_CAN_MAX_RECEIVE_QUEUE_TIMEOUT_MS CONFIG_ODRIVE_CAN_MAX_RECEIVE_QUEUE_TIMEOUT_MS
#else // The max time to wait for acessing the CAN driver receive queue
#define ODRIVE_CAN_MAX_RECEIVE_QUEUE_TIMEOUT_MS 10
#endif

#define ODRIVE_MAX_MESSAGE_TIMEOUT_MS MAX(ODRIVE_HEARTBEAT_TIMEOUT_MS, ODRIVE_ENCODER_ESTIMATES_TIMEOUT_MS)

#endif // ODRIVE_CONF_H